#!url=https://raw.githubusercontent.com/chen86860/scripts/main/shadowrocket/modules/yangjibao.module
#!name=yangjibao
#!desc=养基宝去广告，并将账户 subscribe_status 改为 1

[URL Rewrite]

^https?:\/\/app-api\.yangjibao\.com\/unify_ad - reject-dict
^https?:\/\/app-api\.yangjibao\.com\/content\/v1\/ad\/config - reject-dict

[Body Rewrite]

http-response-jq ^https?:\/\/app-api\.yangjibao\.com\/users\/v1\/account(\?.*)?$ '.data.subscribe_status = 1 | .data.vip_label = true | .data.has_stock_hold = true | .data.has_stock_option = true | .data.is_pay = true | .data.open_free_vip_sign = true | .data.show_bkxh = true'

[MITM]

hostname = %APPEND% app-api.yangjibao.com
